### ISSUE TITLE
Language Selection

### ISSUE THREAD

**Issue by mpearon** [jeffwcx/rest-while#1]
It appears that the extension does not support language selection.  Any plans for this functionality?
I can extrapolate the time, but it would be nice to see the rest of the text in English.
![info](https://user-images.githubusercontent.com/7157790/32286904-f7c8f0fe-befc-11e7-8e59-9815c7ad1f30.JPG)
![status](https://user-images.githubusercontent.com/7157790/32286905-f7e60eaa-befc-11e7-8ca6-b63671d3b1b3.JPG)

**Comment by mpearon** [comment]
I hate to be a bother, but are there any updates on this?

**Comment by jeffwcx** [comment]
I'm sorry, but I thought nobody used it. I'll add language support over the weekend.In addition, do you have any suggestions on the functionality of the plugin?

**Comment by jeffwcx** [comment]
@mpearon Already update, add support for English and Chinese. But I change the posting address. Here is the new address [https://marketplace.visualstudio.com/items?itemName=jeffwong.rest-for-a-while](https://marketplace.visualstudio.com/items?itemName=jeffwong.rest-for-a-while). I have already forgot the vscode's `Personal Access Token` 😓
